[features]
seeds = false
skip-lint = false
[programs.localnet]
basic1 = "2dquKA6oybP8pFeAPsjYD5MckyDKs1tkYeSmazeveJYm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ubuntu/new-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
